all:vector iterator array deque string initializer_list
initializer_list:initializer_list.cpp
	g++ -o initializer_list initializer_list.cpp -std=c++11
string:string.cpp
	g++ -o string string.cpp -std=c++11
deque:deque.cpp
	g++ -o deque deque.cpp -std=c++11
array:array.cpp
	g++ -o array array.cpp -std=c++11
iterator:iterator.cpp
	g++ -o iterator iterator.cpp -std=c++11
vector:vector.cpp
	g++ -o vector vector.cpp -std=c++11
